server:
  port: 8081

spring:
  profiles:
    active: dev

javafx:
  title: DocOrbit IMPorter
  stage:
    resizable: true
  main:
    tree: true
    toolbar: true

logging:
  level:
    com.docorbit: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
